language: node_js

script:
  - npm run-script test_coverage_baseline
  - npm run-script test
  - npm run-script merge_test_coverage
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run-script saucelabs; fi

after_success: npm run-script coveralls

env:
  global: 
    - secure: "sa+Z54V4qjHIEjGitEExUDG6qAbGzYLkg5TnlGsFtMdmIw/ARnGWMIShCdyAciWyQ5RD+1F14DjgOiFQyd3w6ejr/FOsqHRcS742fqfn/ply3NokExkl0carpnuOf64eaj3vmKGM4kuZ9mxhOPnvBP6vbPSPFKuvbiGGpZf5SRw8/Z++3hF0eojTe8W/IOWZApt0z5Nc0e+309UtlsTSPVXAnoQnZ5I1ItOSe4cUkaRH19jEHTIHonjpoW62R8la0xzDYyUOGbUiTL00BtXJLjlgk8Ec5hFwy/BNNwdPebbckTpIrqEgHMftun7YkIFTUwldDnhtApPQlwreEOgL5FNpEhxACjPLQ9SgEdz18zkbyhhVN7LIVOwcbVTAxcjzMYWMW8584tOI6qBcyKT8NmGcpWj0yv5PMgzLtPbv3y1RzsnuXDFwGv5q+rHDiNMC9moyrgLQpv31Pzy0wLjdrbrX09cMj5A4N9ReKtYYN8NJtPFsgeRU535BHiTD+KSQ3nhzGzG2kV32p4UUBvg0l6+GOK76TNSPn79t82BCUFNekYT/BChfRsFJppJ7CVmNRnhIkrDQfQ53qM8vFJ9EidpcZ1DkoO1vRC6Vmar/pxXkTdFQGFRJNJOgJrgo56nBZnzSeICO7ct100iiJ9hzZlq1SNn89+LWfg5o/vlh0Gs="
    - secure: "dFyLfLc4nrSeZfANnhVWkRLFUbrdu8usONzOaa7kVjA3xOaUHNjAiUuivCpICgzwSfMSL11KuyI740K31cWIGrxgV7WiIudphs/OsCX1wBjHx6Jb2aD3ffSBc0z5eIcDwLrcZLHsdL5wd1SF7UqodipS3oGMh+8b5C4Vaqr0AvI226BMVMd85VFcBGZ5c6TJ9rRJtExnTnFbxnk64E2SHFlxhOUtdl5c961cqk9VzNLdMvJVmW5Ny9TzkQAU4GbmeLvZJQ+abpbo324G3MSmPYVmlVmv1NhIMO25bcBI4e/Uuh635pDk4BlXUM+NjIwRDu3jPPToAJrm0xtPsTHt4x+C2hdFqMlfNFbC+zBhXzOJwisPmOHpB6B4KfqdQ5XdmUpumblpCdrO/ePTFt/anCDcoti9mhl/WAMgcrVx0zAOFDNMjWm92j1REPr4F7e/zfE08FJf+yXnzH0l4nSSknNFdUCKpcAVvZRQshi9gHMvqZJPx3WQGgGvx2b+ayuL9J+WJSIjohooCG98heBw0ekmKg1Rin2QHNoHgN8j3CR+d9TOVWy/NGEgmv5JfJUttOyhA9acY3TEirxb7YysmdVvbErCf+HnTHeeGGI8m3awTaQkc7mfjlmsAc7hKfEF26Q0/Ygr3VGHTzfNYpGzU38ovWRcigNfyUimShv4xNc="
